# my config
version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: nhtua/react-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASS
      - docker/build:
          image: $DOCKER_IMAGE
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  # deploy:
  #   executor: docker/docker
  #   steps:
  #     # Please add $SSH_KEY_FINGERPRINT, $DEPLOYED_USER@ and DEPLOYED_SERVER to project's environment
  #     - add_ssh_keys:
  #         fingerprints:
  #           - $SSH_KEY_FINGERPRINT
  #     - run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER './deploy.sh'

workflows:
  my-pipeline:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
      # uncomment the 3 following lines to enable deploying
      # - deploy:
      #     requires:
      #       - build-and-push
